server:
  port: 8089
    # 下面这个参数是为解决问题而新增的
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: XIA
    password: xiahao12
  redis:
    host: 192.168.2.108
    port: 6379
    password: redis
    max-wait: -1
    max-idle: 8
    min-idle: 0
    max-active: 10
    timeout: 30000


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql